#Information about how to use the Requests module can be found at:
#http://docs.python-requests.org/en/master/user/quickstart/

import requests

# Create a dictionary of name/value pairs to send to weather underground
weatherData = {'ID':'KCASACRA194',
               'PASSWORD':'yxhczp7r',
               'dateutc': 'now',
               'action':'updateraw',
               'tempf':'62'}


#Send a "get" request to the weather undergound website.  Include the parameters.
r = requests.get('https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php',
                 params = weatherData)

print(r.url)  #Print the url that was generated by the get request
print(r.text) #Print the response that we got from the website.  This should be "success".
